# Generated by Django 5.0.7 on 2024-08-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Pictur',
        ),
    ]
