# Generated by Django 5.0.7 on 2024-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_pictur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pictur',
            field=models.ImageField(default='upload/products/default.jpg', upload_to='upload/products/'),
        ),
    ]
