# Generated by Django 5.0.7 on 2024-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_pictur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pictur',
            field=models.ImageField(upload_to='upload/products/'),
        ),
    ]
