# Generated by Django 5.0.7 on 2024-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_offer_alter_product_pictur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OfferPrice',
            field=models.IntegerField(default=0),
        ),
    ]
