# Generated by Django 5.0.7 on 2024-08-05 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
