# Generated by Django 5.0.7 on 2024-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
